Twingate/terraform-provider-twingate

Makefile
> JIRA Ticket URL: https://twingate.atlassian.net/browse/TG-2994
- `make docs` now uses `GOBINPATH` to run `tfplugindocs`
=> Support doc generation via Makefile

README.md
=> Update README with contribution info

README.md
=> [DNM] README change - Fix coveralls link

docs/guides/aws-deployment-guide.md
> JIRA Ticket URL: TG-3276
> Notion spec URL:
- Correct missing equals sign in AWS guide
- Remove reference to using Admin Console for obtaining identifiers
- Add link to Admin API
=> TG-3276 | Documentation fixes

main.go, twingate/client.go, twingate/client_test.go, twingate/provider.go, twingate/provider_test.go, twingate/twingate_sweeper_test.go, version/version.go
- JIRA Ticket URL: TG-3147
Go releaser providers twingate provider version to user-agent
=> TG-3147 | user agent from go releaser

docs/index.md, twingate/client.go, twingate/client_connector_test.go, twingate/client_connector_tokens.go, twingate/client_connector_tokens_test.go, twingate/client_resource_test.go, twingate/client_test.go, twingate/provider.go, twingate/provider_test.go, twingate/resource_connector_tokens.go, twingate/resource_connector_tokens_test.go, twingate/resource_resource_test.go, twingate/twingate_sweeper_test.go
- JIRA Ticket URL: https://twingate.atlassian.net/browse/TG-4820
- Added support for HTTP retries
- Provider configuration for HTTP timeout and max retry
=> TG-4820 | Added support for http retries

README.md
Removed unnecessary image from README
=> Remove unnecessary image in README

dangerfile.js
- No longer require JIRA\Github issue
- Try to ensure description is somewhat meaningful by checking its not the default text
=> Relax danger file PR validation rules

.circleci/config.yml, go.mod, go.sum, golangci.yml
- fixing linter issues
- update ci docker image
=> Dependabot/go modules/GitHub.com/hashicorp/terraform plugin sdk/v2 2.16.0

docs/resources/connector.md, examples/resources/twingate_connector/import.sh, twingate/resource_connector.go, twingate/resource_connector_test.go
Github Issue: https://github.com/Twingate/terraform-provider-twingate/issues/94
- Fixed connector import - set network_id
=> Fix importing a connector

twingate/resource_resource.go, twingate/resource_resource_test.go
Github Issue: https://github.com/Twingate/terraform-provider-twingate/issues/82
- ports reordering does not trigger changes
=> Fix ports reordering

README.md
Github Issue: #107 
Updated development requirements on README
=> README - Update requirements

twingate/resource_resource.go, twingate/resource_resource_test.go
Github Issue: https://github.com/Twingate/terraform-provider-twingate/issues/121
- added fix for ports range comparison
=> Fix ports compression issue

docs/data-sources/group.md, twingate/client_group.go, twingate/client_group_test.go, twingate/datasource_group.go, twingate/datasource_group_test.go
Resolves (github issue): https://github.com/Twingate/terraform-provider-twingate/issues/137
- added new fields: type and is_active
=> Group datasource: added type and is_active

twingate/datasource_connectors.go, twingate/datasource_connectors_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/144
- added fix for empty connectors list
=> Fix for empty connectors list - datasource connectors

.github/workflows/ci.yml, .github/workflows/verify-pr.yml
Resolves #164 
- PR Checks - add edit type so that it reruns when description is edited
=> Require environment for ACC tests

CODEOWNERS
Protect `.github` folder from changes - requires extra eyes to review
=> Protect .github folder

.github/workflows/ci.yml
=> CI: remove environments

.github/workflows/smoketests.yml, twingate/datasource_connector_test.go, twingate/datasource_connectors_test.go, twingate/datasource_group_test.go, twingate/datasource_groups_test.go, twingate/datasource_remote_network_test.go, twingate/datasource_resource_test.go, twingate/datasource_resources_test.go, twingate/resource_connector_sweepers_test.go, twingate/resource_connector_test.go, twingate/resource_connector_tokens_test.go, twingate/resource_group_sweeper_test.go, twingate/resource_group_test.go, twingate/resource_remote_network_sweepers_test.go, twingate/resource_remote_network_test.go, twingate/resource_resource_sweeper_test.go, twingate/resource_resource_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/167
- added test prefix
=> Add unique name to acc tests

.github/workflows/ci.yml, .github/workflows/smoketests.yml, twingate/datasource_connectors_test.go, twingate/datasource_remote_network_test.go, twingate/datasource_resources_test.go, twingate/datasource_user_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/167
- fix acc test
=> Fix unstable test in parallel execution

docs/index.md, twingate/provider.go
=> Increase DefaultHTTPMaxRetry to 10

twingate/resource_connector.go, twingate/resource_connector_tokens.go, twingate/resource_group.go, twingate/resource_remote_network.go, twingate/resource_resource.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/167
- added wait time after resource creation
=> Fix acc tests

go.mod, go.sum
Resolves  PR https://github.com/Twingate/terraform-provider-twingate/pull/201
- have run locally acceptance test, to check that all test works with new sdk version
=> Upgrade terraform-plugin-sdk to version 2.24.0

twingate/resource_connector_tokens.go, twingate/resource_resource.go
Resolves `wait for resource`
- removed last usage
=> Remove `wait for resource`

.github/workflows/smoketests.yml
=> Reduce Smoketest frequency

docs/data-sources/remote_network.md, docs/resources/remote_network.md, twingate/internal/client/query/remote-network-by-id-read.go, twingate/internal/client/query/remote-network-create.go, twingate/internal/client/query/remote-network-update.go, twingate/internal/client/remote-network.go, twingate/internal/model/remote-network.go, twingate/internal/provider/datasource/remote-network.go, twingate/internal/provider/resource/remote-network.go, twingate/internal/test/acctests/resource/remote-network_test.go, twingate/internal/test/client/remote-network_test.go, twingate/internal/test/models/remote_network_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/231
- added `location` property to remote-network resource and datasource
=> Feature: added remote network `location` property

twingate/internal/client/client.go, twingate/internal/client/client_test.go, twingate/internal/test/client/client_test.go, twingate/provider.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/228
- fix API token test
=> Fix: client lazy init test

twingate/internal/test/acctests/resource/service-account_test.go, twingate/internal/test/acctests/resource/service-key_test.go
Resolves failing acctest
- added wait pause
=> Fix: acctest service account

docs/data-sources/security_policies.md, docs/data-sources/security_policy.md, twingate/internal/provider/datasource/security-policies.go, twingate/internal/provider/datasource/security-policy.go
=> Docs updates for security polic(ies) data sources

twingate/internal/test/acctests/datasource/remote-networks_test.go
Resolves temporary failing acctest
- changed static prefix name to random one
=> Fix acctest: remote-networks read

scripts/test.sh
Resolves issue with temporary failing tests
- added `re-run` flag
=> Re-run failing tests

twingate/internal/provider/resource/resource.go, twingate/internal/test/acctests/resource/resource_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/284
- fix setting up flag values from terraform data
- updated tests to cover bug case
=> Fix resource visible flags

.github/workflows/release.yml
Resolves #297
- Update to latest actions on release.yml (note that we already did this, and are using v3, on our other CI actions)
=> Fix goreleaser actions

twingate/internal/client/connector.go, twingate/internal/client/resource.go, twingate/internal/client/variables.go, twingate/internal/client/variables_test.go
- added support for pointer values to gql internal lib
- simplified client code with optional flags
=> Fix nullable pointer values

docs/resources/resource.md, twingate/internal/attr/group.go, twingate/internal/client/query/query_test.go, twingate/internal/client/query/resource-create.go, twingate/internal/client/query/resource-read.go, twingate/internal/client/query/resource-update.go, twingate/internal/client/resource.go, twingate/internal/model/resource.go, twingate/internal/provider/resource/helper.go, twingate/internal/provider/resource/resource.go, twingate/internal/test/acctests/resource/resource_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/315
- add `alias` attribute
=> Added optional alias attribute

docs/data-sources/connector.md, docs/data-sources/group.md, docs/data-sources/resource.md, docs/data-sources/security_policies.md, docs/data-sources/security_policy.md, docs/data-sources/user.md, docs/resources/resource.md, twingate/internal/provider/datasource/connector.go, twingate/internal/provider/datasource/group.go, twingate/internal/provider/datasource/resource.go, twingate/internal/provider/datasource/security-policies.go, twingate/internal/provider/datasource/security-policy.go, twingate/internal/provider/datasource/user.go, twingate/internal/provider/resource/resource.go
=> Doc string updates for v1.0.0-rc2

docs/data-sources/user.md, docs/data-sources/users.md, twingate/internal/attr/common.go, twingate/internal/attr/group.go, twingate/internal/client/query/user-read.go, twingate/internal/model/user.go, twingate/internal/provider/datasource/converter_test.go, twingate/internal/provider/datasource/user.go, twingate/internal/provider/datasource/users.go, twingate/internal/test/models/user_test.go
- added `type` to user/users datasource
=> Added user type to datasource

docs/data-sources/user.md, docs/data-sources/users.md, twingate/internal/provider/datasource/user.go, twingate/internal/provider/datasource/users.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/326
- added deprecation message
=> Deprecation message for attribute is_admin

twingate/internal/client/group.go, twingate/internal/client/query/group-read.go, twingate/internal/client/resource.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/327
- added missing cursor
=> Fix: added missing cursor

docs/guides/aws-deployment-guide.md, templates/guides/aws-deployment-guide.md.tmpl
- Update documentation for the AWS deployment guide to be consistent with the twingate_resource docs
=> Update aws-deployment-guide.md for changes to twingate_resource

.github/workflows/ci.yml, twingate/internal/client/query/resource-read.go, twingate/internal/client/query/resource-service-accounts-read.go, twingate/internal/client/resource.go, twingate/internal/provider/resource/resource.go, twingate/internal/test/acctests/datasource/resource_test.go, twingate/internal/test/client/resource_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/339
- updated resource read/update queries to read service accounts
=> Fetch serviceAccounts from resource graphql query

go.mod, twingate/internal/client/client.go, twingate/provider.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/338
- added header to all requests with correlation id
=> Added correlation id

main.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/347
- added provider addr
=> Added provider addr

.github/workflows/ci.yml, twingate/internal/test/acctests/datasource/service-accounts_test.go, twingate/internal/test/acctests/resource/resource_test.go
Resolves failed smoke test.
Test passes on the fork: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/5533884619/jobs/10098096135
- fix tests
=> Fix failed tests

.github/workflows/ci.yml, golangci.yml, twingate/internal/model/resource.go, twingate/internal/provider/datasource/converter_test.go, twingate/internal/provider/resource/resource.go, twingate/internal/test/acctests/resource/resource_test.go, twingate/internal/test/models/resource_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/351
Test results: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/5619071325
- fix policy conversion logic
=> Fix protocols block

.github/workflows/ci.yml, twingate/internal/test/acctests/helper.go
Resolves issue with smoke tests
Test passes: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/5871283964?pr=24
- replaced delete queries with read query
=> Fix: check resource deleted with read query

.github/workflows/ci.yml, twingate/internal/client/connector-tokens.go, twingate/internal/client/operation.go, twingate/internal/client/query/connector-token-generate.go, twingate/internal/test/client/client_test.go, twingate/internal/test/client/connector-tokens_test.go
Resolves connector-token client
Tests passes: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/5944083984/job/16120615350?pr=27
- code cleanup
=> Added cleanup code

.github/workflows/ci.yml, twingate/internal/client/query/query_test.go, twingate/internal/client/query/resource-read.go, twingate/internal/provider/resource/resource.go, twingate/internal/test/acctests/resource/resource_test.go, twingate/internal/test/client/resource_test.go
Tests passes: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/6252952401?pr=32
Resolves provider crash
- fix resource protocol validation
=> Fix: resource protocols

.github/workflows/ci.yml, docs/resources/resource.md, examples/resources/twingate_resource/resource.tf, golangci.yml, twingate/internal/client/query/resource-update.go, twingate/internal/client/resource.go, twingate/internal/provider/resource/resource.go, twingate/internal/test/acctests/helper.go, twingate/internal/test/acctests/resource/resource_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/430
Test passes: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/7172949273
- added optional attribute `is_active` to twingate_resource
=> Added optional attribute is_active to twingate_resource

twingate/internal/provider/resource/resource.go
=> Fix url address to migration guide

.github/dependabot.yml
Make dependabot update github action dependencies
=> chore: Dependabot for github actions

.github/workflows/automerge-dependabot.yaml
Resolves #512
- Add workflow to auto merge Dependabot PRs
=> Auto-merge Dependabot PRs

twingate/internal/provider/resource/resource-v1.go
Resolves issue with upgrading from previous provider version
- fix object atribute types
=> Fix schema upgrade

main.go, twingate/internal/client/client.go, twingate/internal/client/client_test.go, twingate/internal/client/errors.go, twingate/internal/test/acctests/helper.go, twingate/internal/test/client.go, twingate/internal/test/client/client_test.go, twingate/internal/test/sweepers/sweeper_test.go, twingate/provider.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/523
- made client agent name configurable
=> Cstomized agent client name

.github/workflows/release.yml
Reverts Twingate/terraform-provider-twingate#541
=> Revert "Bump goreleaser/goreleaser-action from 5 to 6"

.github/workflows/ci.yml, .github/workflows/smoketests.yml, .tool-versions
Update to latest supported TF versions (1.7.* is EOL)
=> chore: Update TF versions in CI

twingate/internal/client/client.go
Resolves too many requests
- added request rate limiter
=> Added rate limit for requests

docs/guides/migration-v1-to-v2-guide.md, templates/guides/migration-v1-to-v2-guide.md.tmpl
- Remove a "j" that snuck its way into the docs
=> Remove an errant 'j'

.github/ISSUE_TEMPLATE/1-bug.yml, .github/ISSUE_TEMPLATE/2-feature.yml, .github/ISSUE_TEMPLATE/config.yml
- Adds issue templates to the repo
=> Add issue templates

.github/ISSUE_TEMPLATE/2-feature.yml
- Forgot to make issue names unique
=> Fix issue names

.github/workflows/ci.yml, golangci.yml, twingate/internal/client/cache.go, twingate/internal/client/cache_test.go, twingate/internal/client/group.go, twingate/internal/model/group.go, twingate/internal/model/resource.go, twingate/internal/provider/datasource/groups.go
Tests passes: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/14346067365
- added search by name for cached resources
=> Feature: search groups by name

.github/workflows/smoketests.yml
- upgraded terraform and tofu versions for smoke tests
=> Upgraded terraform and tofu versions

.github/workflows/ci.yml, docs/index.md, examples/provider/provider.tf, twingate/internal/attr/provider.go, twingate/internal/client/cache.go, twingate/internal/client/cache_test.go, twingate/internal/client/client.go, twingate/internal/client/client_test.go, twingate/internal/client/group.go, twingate/internal/client/resource.go, twingate/internal/test/client.go, twingate/internal/test/client/client_test.go, twingate/internal/test/sweepers/sweeper_test.go, twingate/provider.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/699
Tests passes: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/14899062801
- added cache options for provider
- added cache lazy load
=> Feature: cache lazy load

.github/workflows/ci.yml, twingate/internal/provider/resource/resource.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/719
Tests passes: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/15142571000
- fix panic on resource import
=> Fix panic on resource import

.github/workflows/ci.yml, docs/resources/user.md, examples/resources/twingate_user/resource.tf, twingate/internal/attr/user.go, twingate/internal/client/query/user-create.go, twingate/internal/client/user.go, twingate/internal/model/user.go, twingate/internal/provider/resource/user.go, twingate/internal/test/acctests/datasource/users_test.go, twingate/internal/test/acctests/resource/user_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/743
Tests passes[UPD-1]: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/16481917900/job/46598200283
- removed attribute `send_invite`
=> Fix: removed attribute send_invite

.goreleaser.yml
Resolves goreleaser issue
- fix goreleaser hook with bash shell
=> Added explicitly bash environment

.github/workflows/ci.yml, twingate/internal/provider/resource/resource.go, twingate/internal/test/acctests/resource/resource_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/753
Tests passes: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/17333203845
- fix securilty_policy update
=> Fix security_policy_id on resource update
