twingate/client.go, twingate/client_remote_network.go, twingate/client_resource.go
> JIRA Ticket URL: TG-2704 
- When creating a remote network it is not necessary to send an `isActive` argument
=> TG-2704 | isActive parameter is unnecessary and being deprecated

twingate/client_connector.go, twingate/client_connector_test.go, twingate/client_connector_tokens_test.go, twingate/client_remote_network.go, twingate/client_remote_network_test.go, twingate/client_resource.go, twingate/client_resource_test.go, twingate/resource_connector.go, twingate/resource_connector_sweepers_test.go, twingate/resource_remote_network.go, twingate/resource_remote_network_sweepers_test.go
- Changed internal client uses in provider, so from terraform provider we don't need to use graphql types
=> Updated graphql client in provider to expose string types instead of graphql

go.mod, go.sum
Github Issue:
- fix go.mod merge conflicts
=> Dependabot/go modules/GitHub.com/jarcoal/httpmock 1.2.0

CHANGELOG.md
We’re tracking changes via description of Github Releases
=> Remove CHANGELOG.md as its not being used

examples/resources/twingate_connector/resource.tf, go.mod, go.sum, twingate/resource_connector.go, twingate/resource_connector_test.go
Github Issue: https://github.com/Twingate/terraform-provider-twingate/issues/79
- added fix to not allow change remote_network_id for existing connector
=> Not allow change remote_network_id for existing connector

.github/workflows/release.yml
Change the `Import GPG Key` task to use `crazy-max/ghaction-import-gpg@v5` based on hashicorp recommendation:
=> Switch to crazy-max/ghaction-import-gpg

docs/index.md
Prospect thought they needed Enterprise Tier to use Terraform and referenced this doc. Since we changed our tiers this is no longer correct so submitting a PR for this.
=> Remove reference to requiring Enterprise tier for API key

.github/workflows/ci.yml, .github/workflows/smoketests.yml
Initial work on #167 
- Adds `TEST_UNIQUE_VALUE` env var to be used by tests to isolate themselves
=> Add `TEST_UNIQUE_VALUE` to be used to isolate ACC Tests runs

.github/workflows/ci.yml, .github/workflows/verify-pr.yml, Makefile
- Downgraded `lint` as new version has breaking changes. We already have a separate PR to upgrade it - https://github.com/Twingate/terraform-provider-twingate/pull/170
- Removed acceptance-tests from forked PRs
- Added concurrency settings so that pushing a change cancels previous running build
-
=> CI: Dont run acceptance tests from forks

.github/workflows/ci.yml, .github/workflows/smoketests.yml
Adding cache to go dependencies to reduce random failures due to networking errors on `go mod download`
=> CI: Cache go dependencies

docs/data-sources/user.md, docs/data-sources/users.md, golangci.yml, twingate/datasource_user.go, twingate/datasource_users.go
Resolves #198 
Ignores deprecated linters:
```
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'nosnakecase' is deprecated (since v1.48.1) due to: The repository of the linter has been deprecated by the owner.  Replaced by revive(var-naming).
WARN [runner] The linter 'ifshort' is deprecated (since v1.48.0) due to: The repository of the linter has been deprecated by the owner.
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet …
```
=> Update lint rules

twingate/client.go, twingate/client_connector_tokens.go, twingate/client_connector_tokens_test.go
Resolves #199 
- Calls `/api/v4/connector/validate_tokens` instead of `/api/v1/refresh` - call signature is the same
=> CUS-3 | Migrate token verification to v4 API

twingate/datasource_connector_test.go, twingate/datasource_connectors_test.go, twingate/datasource_group_test.go, twingate/datasource_groups_test.go, twingate/datasource_remote_network_test.go, twingate/datasource_resource_test.go, twingate/datasource_resources_test.go, twingate/datasource_user_test.go, twingate/datasource_users_test.go, twingate/resource_connector_test.go, twingate/resource_connector_tokens_test.go, twingate/resource_group_test.go, twingate/resource_remote_network_test.go, twingate/resource_resource_test.go, twingate/test_utils.go
Fixes acceptance test random failures
Add a delay between the test's `config` phase and `check` phase. As check usually query replica DBs there's a chance of a small replication delay
=> Fix acc tests

twingate/internal/client/remote-network.go, twingate/internal/provider/resource/remote-network.go, twingate/internal/test/acctests/resource/remote-network_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/239
- fix update remote-network name
```
~ resource "twingate_remote_network" "this" {
id       = "UmVtb3RlTmV0d29yazoxODgzMQ=="
~ location = "AWS" -> "OTHER"
name     = "aws-euw2"
}
```
in this case user would need to add new line to the terraform resource to keep the same value for location
`location = "AWS" `
=> Fix remote-network update

.goreleaser.yml
Resolves #244 
- Make new releases as drafts so we publish them after Changelog is written
=> Release as draft first

twingate/internal/provider/resource/resource.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/276
- by default authoritative flag won't generate drift, when user moves to new version
=> Improved resource authoritative flag behaviour

twingate/internal/client/client.go, twingate/internal/client/client_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/282
- added check for TLS certificate error, to break re-try loop in this case
=> Fix: prevent provider from hanging on invalid server URL

.github/workflows/ci.yml
Resolves #300 
Based on https://endoflife.date/terraform versions 1.0 and 1.1 are now dead so we should be testing on 1.2, 1.3 and latest
=> Fix acc tests terraform versions (Remove ACC tests on EOL TF versions)

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/smoketests.yml
Resolves #297
- Fix Go caching - `setup-go` does caching and `actions/cache@v3` wasn't really doing anything but taking a lot of time
- Fix goreleaser (proof: https://github.com/Twingate/terraform-provider-twingate/actions/runs/4349434349)
=> CI Fixes - Goreleaser, Cache

golangci.yml
- Fixed `depguard` settings
- Disabled `gomoddirectives` as we're not using go modules
=> New golangci-linter settings

.github/workflows/smoketests.yml
- `latest` moved to be 1.5 but we still want to tst on 1.4. So this explicitly lists all versions we currently support
=> Dont Smoke-Test terraform versions no longer supported

docs/index.md, twingate/provider.go, twingate/v2/provider.go
Resolves #403 
- Changing the default timeout to `35s` until we have a better solution for idepotency
=> Change timeout to 35s

docs/guides/aws-deployment-guide.md, examples/ami/ami.tf
Resolves #525
- Update AWS modules with newer versions
- Remove enable_classiclink_dns_support it is no longer supported by AWS
- Add default encryption to root EBS volume
- Minor fixes to support newer versions of modules
=> Update AWS docs

twingate/internal/provider/resource/resource.go, twingate/internal/test/acctests/resource/resource_test.go
The previous CIDR regex ended with a `?` after the group capturing the slash character. I've removed the `?` and added tests to ensure that Resources with a normal IP address can be created with the browser flag.
Resolves #545
=> Fix CIDR regex

.github/workflows/ci.yml, twingate/internal/provider/resource/resource.go, twingate/internal/test/acctests/resource/resource_test.go
Resolves https://github.com/Twingate/terraform-provider-twingate/issues/552
Tests passes: https://github.com/vmanilo/terraform-provider-twingate/actions/runs/9681717928/job/26712959782
- fix crash on nil resource
=> Fix: crash on invalid alias value

.github/workflows/ci.yml, twingate/internal/client/client.go, twingate/internal/client/group.go, twingate/internal/provider/datasource/all-datasources.go, twingate/internal/provider/datasource/group.go, twingate/internal/provider/datasource/groups.go
- update group query names
use cases:
1. Group resource
1. Init cache at beginning of provider: op will be `cache_readGroups` for first call and then `cache_readGroups_readGroupsAfter` for all pages
2. Create a group and read it after - op name is just `readGroup`
2. Group datasource (singular) - op name is `datasource_readGroup`
3. Group datasource (plural) - op name is `datasource_readGroups` and for pages `datasource_readGroups_readGroupsAfter`
=> Updated group query names

docs/resources/resource.md, examples/resources/twingate_resource/resource.tf
- there was a typo. it says `acoount` and means `account`
=> Fix: acoount typo

.github/workflows/close-stale-issues.yml
A few planned issues were closed as stale. This change adds the `backlog` label as an exempt issue label so that we can mark any issues that are planned.
=> [Workflows] Ignore issues with the backlog label
